### ISSUE TITLE
deploy built site from gh-pages

### ISSUE THREAD

**Issue by lazarusA** [lazarusA/TemplateDocsVitePress.jl#1]
@asinghvi17 here a list of issues. Thanks for taking a look. This is how I think things should be, but of course any alternative/better ideas are very welcome. 

TODOS:

- [ ] 1. Deploy docs from gh-pages
- [ ] 2. Split between dev and tag released versions
- [ ] 3. Preview PRs

# On one 
this is what I currently have: 

Currently the CI Documenter sends the necessary files 

```
docs
    > .vitepress
    config.mts
package-lock.json
package.json
```
to 

gh-pages
```
 > dev
```
but, two things, deploy.ylm doesn't work and/or doesn't know that necessary files are in `dev`, namely, 

https://github.com/lazarusA/TemplateDocsVitePress/blob/069e4fe74f6f1861f80faa9228de823f74b53c3e/.github/workflows/deploy.yml#L42

and (setting in the package.json file)

https://github.com/lazarusA/TemplateDocsVitePress/blob/069e4fe74f6f1861f80faa9228de823f74b53c3e/.github/workflows/deploy.yml#L49

# For two, 
we could use https://vitepress.dev/guide/i18n, where for us

Only .md content should be pushed into those newly created folders at each release stage.

```
docs/ # the outer level is dev
├─ v1.0/
│  ├─ foo.md
├─ v2.0/
│  ├─ foo.md
├─ foo.md
```

# On 3, maybe something similar to two, namely
```
docs/ # the outer level is dev
├─ v1.0/
│  ├─ foo.md
├─ PR1/
│  ├─ foo.md
├─ foo.md
├─ PR2/
│  ├─ foo.md
├─ foo.md
```
and then delete them when merged into `dev`.

**Comment by asinghvi17** [comment]
Yes I see what you mean.  I don't think i18n is the way to go - imo we will have to modify the Vitepress configuration before build time, to specify which folder it will deploy in once pushed to gh-pages.
